# Generated by Django 5.1.3 on 2025-03-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100)),
                ('product_img', models.ImageField(blank=True, null=True, upload_to='product')),
                ('product_name', models.CharField(max_length=100)),
                ('product_rating', models.ImageField(blank=True, null=True, upload_to='rating')),
                ('product_count', models.IntegerField()),
                ('product_price', models.FloatField()),
                ('key_word', models.TextField()),
            ],
        ),
    ]
