# Generated by Django 5.1.3 on 2025-03-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='key_word',
            field=models.CharField(max_length=500),
        ),
    ]
